### ISSUE TITLE
Is the PoloDB Discord still a thing ?

### ISSUE THREAD

**Issue by DataHearth** [vincentdchan/polodb-docs#4]
Hey!

I was wondering if the Discord is still active or even exists ?

The provided link in the navbar is not valid. Wondering if it needs just an update ?

I think it's kinda cool to interact with the community directly outside of issues 🙂 .

Thanks!

**Comment by vincentdchan** [comment]
Yes, I do have a Discord account. The link is outdated. I will update that.
And I am always online.
I do want to build a community, but I don't have any idea how to do it yet.

**Comment by vincentdchan** [comment]
The discord link is updated to: https://discord.gg/NmGQyVx6hH
